export const keys = {
  GET_EXHIBITION: ["GET_EXHIBITION"],
  GET_ARTGRAM: ["GET_ARTGRAM"],
  GET_ARTGRAMDETAIL: ["GET_ARTGRAMDETAIL"],
  GET_ARTGRAMCOMMENTS: ["GET_ARTGRAMCOMMENTS"],
  GET_DETAILEXHIBITION: ["GET_DETAILEXHIBITION"],
  GET_USERPROFILE: ["GET_USERPROFILE"],
  GET_MAINMOSTLIKE : ["GET_MAINMOSTLIKE"],
  GET_MAINCURRENTARTGRAM : ["GET_MAINCURRENTARTGRAM"],
  GET_MAINNEARESTEXHIBITION : ["GET_MAINNEARESTEXHIBITION"],
  GET_MAINOPENEXHIBITIONBYDATE : ["GET_MAINOPENEXHIBITIONBYDATE"],
  GET_MAINPERSONALEXHIBITION : ["GET_MAINPERSONALEXHIBITION"]
};
