export const keys = {
  GET_EXHIBITION: ["GET_EXHIBITION"],
  GET_ARTGRAM: ["GET_ARTGRAM"],
  GET_ARTGRAMDETAIL: ["GET_ARTGRAMDETAIL"],
  GET_ARTGRAMCOMMENTS: ["GET_ARTGRAMCOMMENTS"],
  GET_DETAILEXHIBITION: ["GET_DETAILEXHIBITION"],
  GET_USERPROFILE: ["GET_USERPROFILE"],
};
