export const keys = {
  GET_EXHIBITION: ["GET_EXHIBITION"],
  GET_ARTGRAM: ["GET_ARTGRAM"],
  GET_ARTGRAMDETAIL: ["GET_ARTGRAMDETAIL"],
  GET_ARTGRAMCOMMENTS: ["GET_ARTGRAMCOMMENTS"],
  GET_DETAILEXHIBITION: ["GET_DETAILEXHIBITION"],
  GET_USERPROFILE: ["GET_USERPROFILE"],
  GET_LIKEDEXHIBITIONINFO: ["GET_LIKEDEXHIBITIONINFO"],
  GET_LIKEDARTGRAMINFO: ["GET_LIKEDARTGRAMINFO"],
  GET_SCRAPEXHIBITIONINFO: ["GET_SCRAPEXHIBITIONINFO"],
  GET_SCRAPARTGRAMINFO: ["GET_SCRAPARTGRAMINFO"],
  GET_MYARTGRAMINFO: ["GET_MYARTGRAMINFO"],
  GET_MYEXHIBITIONINFO: ["GET_MYEXHIBITIONINFO"],
};
